name: withu_app
description: "withu mobile application"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: 8.0.0

  # Being able to compare objects in Dart
  equatable: ^2.0.5

  # Fetch Data From Api
  dio: 5.7.0
  pretty_dio_logger: ^1.4.0

  # Logging Interceptor
  logging: 1.2.0

  # BloC State Management
  flutter_bloc: 8.1.6

  # Json Annotation
  json_annotation: 4.9.0

  # Code generation
  freezed_annotation: 2.4.4

  # Router
  auto_route: 9.2.2

  # Logging
  logger: ^2.4.0

  # Localization
  intl: ^0.19.0
  easy_localization: ^3.0.7

  # widget related packages
  infinite_scroll_pagination: ^4.0.0
  calendar_date_picker2: ^1.1.7
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # build related
  build_runner: 2.4.12
  json_serializable: 6.8.0
  freezed: 2.5.7

  # lint
  flutter_lints: ^4.0.0

  # router
  auto_route_generator: ^9.0.0

  # Resource manager
  flutter_gen_runner:

  # api mocking
  http_mock_adapter: ^0.6.1

  # Svg
  flutter_svg:

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/


# Derry script manager
scripts:
  # build runner 실행
  build: dart run build_runner build --delete-conflicting-outputs

  # 전체 파일 대상으로 pre-commit hooks 스크립트 실행
  pre-commit: pre-commit run --all-files

# Resource manager
flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true


  colors:
    inputs:
      - assets/color/colors.xml
